name: deployToVercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: npm install
        run: npm install

      - name: run unit tests
        run: npm run test

      - name: run lint
        run: npm run lint

      - name: build
        run: npm run build

      - name: deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-version: latest
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
